### ISSUE TITLE
Custom Code VASL: NPE in ASLBoard$BoardOp.eval

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#1269]
| Bugzilla |  |
|----------|----------|
| ID | BZ10993 |
| Reported | 2014-04-15 20:48:00 +0200 |
| Modified | 2020-08-22 01:52:31 +0200 |
| Product | VASL |
| Component | Board |
| Version | 6.0.0-beta2 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |
| CC | b.easton@exemail.com.au |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/10129) | [Joel Uckelman](mailto:uckelman@nomic.net) 2014-04-15 20:48:00 +0200 text/plain 34036 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) None
<pre>Reported by stuartbrant@gmail.com

Cropping a board in VASL 6.0</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2014-04-15 20:48:10 +0200
<pre>--- Bug imported by uckelman@nomic.net 2014-04-15 20:48 CEST  ---

This bug was previously known as _bug_  at http://www.vassalengine.org/trackershow_bug.cgi?id=
Imported an attachment (id=10129)

The original submitter of attachment 10129 is unknown.
   Reassigning to the person who moved it here: uckelman@nomic.net.</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:29:42 +0200
<pre>*** Bug 10569 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:45:20 +0200
<pre>*** Bug 10885 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:46:44 +0200
<pre>*** Bug 10871 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:46:56 +0200
<pre>*** Bug 10870 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:47:09 +0200
<pre>*** Bug 10845 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:47:25 +0200
<pre>*** Bug 10811 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:47:36 +0200
<pre>*** Bug 10799 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:47:50 +0200
<pre>*** Bug 10677 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2014-06-01 12:49:00 +0200
<pre>*** Bug 10568 has been marked as a duplicate of this bug. ***</pre>

**Comment by derimmer** [comment]
Very old bug. No ability to replicate or investigate. Not worth the effort at this stage.
