### ISSUE TITLE
Red Star Rising module bad custom code: NPE at rsr.RsrAdvanceBase.initialize(RsrAdvanceBase.java:134)

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#1863]
| Bugzilla |  |
|----------|----------|
| ID | BZ12140 |
| Reported | 2015-03-05 04:34:00 +0100 |
| Modified | 2016-10-08 14:13:55 +0200 |
| Product | Other Modules |
| Component | all |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) |
| CC | b.easton@exemail.com.au |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/11253) | [Joel Uckelman](mailto:uckelman@nomic.net) 2015-03-05 04:34:00 +0100 text/plain 75653 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2015-03-05 04:34:47 +0100
<pre>Created attachment 11253
the errorLog</pre>

**Comment by BrentEaston** [comment]
See #2613 for latest updates
