### ISSUE TITLE
VASL: NPE in VASL.build.module.map.ASLBoardPicker$TerrainEditor.actionPerformed

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2154]
| Bugzilla |  |
|----------|----------|
| ID | BZ13010 |
| Reported | 2020-06-05 05:46:00 +0200 |
| Modified | 2020-08-22 01:52:29 +0200 |
| Product | VASL |
| Component | Board |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | TRIAGED |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |
| CC | b.easton@exemail.com.au |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/12068) | [Joel Uckelman](mailto:uckelman@nomic.net) 2020-06-05 05:46:00 +0200 text/plain 20230 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-06-05 05:46:14 +0200
<pre>R_garringer@msn,com

setting up Pto terrain light jungle</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-06-05 05:46:15 +0200
<pre>Created attachment 12068
the errorLog</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2020-06-16 02:20:33 +0200
<pre>*** Bug 12915 has been marked as a duplicate of this bug. ***</pre>

**Comment by derimmer** [comment]
Fixed in vasl6.6.2
