### ISSUE TITLE
Non-ASCII characters in user account name prevent VASL from loading into VASSAL

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2290]
| Bugzilla |  |
|----------|----------|
| ID | BZ13559 |
| Reported | 2020-10-26 03:20:00 +0100 |
| Modified | 2021-05-28 01:45:16 +0200 |
| Product | VASL |
| Component | All |
| Version | 6.6.1 |
| Platform | PC |
| OS | Windows |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Pacman Ghost](mailto:github@muraoka.info) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |
| CC | uckelman@nomic.net |

| Attachments | |
|-------|-------|
| [asciisnip.PNG](http://www.vassalengine.org/files/bz/12921) | [Doug Rimmer](mailto:dougrimmer@rogers.com) 2021-04-16 21:42:00 +0200 image/png 11081 picture of username |

| [vassal-unicode.png](http://www.vassalengine.org/files/bz/12927) | [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 07:55:00 +0200 image/png 224599 screenshot |

| [vassal-error-log.txt](http://www.vassalengine.org/files/bz/12928) | [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 07:56:00 +0200 text/plain 7514 error log |

#### [Pacman Ghost](mailto:github@muraoka.info) 2020-10-26 03:20:54 +0100
<pre>Tiling crashes.

Happens when trying to load VASL 6.6.0 and 6.6.1 into VASSAL 3.4.6, but probably other versions as well.</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-10-26 14:40:47 +0100
<pre>Does this occur in 3.4.7?</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-10-26 14:55:29 +0100
<pre>It would be helpful to have an errorLog from this, as well as some information about the paths involved.</pre>

#### [Pacman Ghost](mailto:github@muraoka.info) 2020-10-27 13:31:36 +0100
<pre>I haven't tried it, but it's a good bet it's happening in other versions.

I have VASSAL 3.2.17 + VASL 6.5.1 (and earlier) loaded into a Windows account whose name contains Japanese characters, so it was working then. Trying to load the new VASSAL+VASL fails, so something's changed since then.

I test vasl-templates in an account with non-ASCII characters to detect exactly these kind of problems :-)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-10-27 22:38:21 +0100
<pre>I'll look into this further when I have an errorLog showing the problem.</pre>

#### [Doug Rimmer](mailto:dougrimmer@rogers.com) 2021-04-16 21:42:44 +0200
<pre>Created attachment 12921
picture of username

Shows username with Cyrillic characters</pre>

#### [Doug Rimmer](mailto:dougrimmer@rogers.com) 2021-04-16 21:44:31 +0200
<pre>I was able to create a user name with cyrillic characters - which I think are non-ascii? Closed vassal/vasl and restarted no problem. Using vassal3.5.4 and the latest vasl dev build.</pre>

#### [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 07:55:50 +0200
<pre>Created attachment 12927
screenshot</pre>

#### [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 07:56:11 +0200
<pre>Created attachment 12928
error log</pre>

#### [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 07:58:19 +0200
<pre>Still not working with VASSAL 3.5.5, on a clean install of Windows 10 x64. Not even getting as far as loading VASL.

See attached screenshot and error log.

User name is 日本.</pre>

#### [Doug Rimmer](mailto:dougrimmer@rogers.com) 2021-04-20 13:53:33 +0200
<pre>Is it fair to assume that this is a VASSAL issue since the error log contains no reference to VASL that I could see? 

I ask this in all seriousness as I am still learning how to understand the error logs.</pre>

#### [Pacman Ghost](mailto:github@muraoka.info) 2021-04-20 14:32:16 +0200
<pre>>>> Is it fair to assume that this is a VASSAL issue since the error log contains no reference to VASL that I could see? 

Yep. That screenshot is from running VASSAL, immediately after having installed it. I didn't even get to the point of loading in the VASL module.</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-28 01:45:16 +0200
<pre>This is likely fixed in 3.5.6, as part of Bugs 14308, 14502, 14503.

Please recheck with 3.5.6.</pre>

**Comment by derimmer** [comment]
> This is likely fixed in 3.5.6, as part of Bugs 14308, 14502, 14503.
> 
> Please recheck with 3.5.6.

Am late getting back to this. Testing with VASSAL3.6.5 and VASL6.6.5-beta1. Was able to add a user with cyrillic characters and open a game. Dice roll reporting in the chat window displayed the characters. The issue appears to be fixed. I am going to close this issue.
