### ISSUE TITLE
[Warriors of God] Initiative button issues and update custom code

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2319]
| Bugzilla |  |
|----------|----------|
| ID | BZ13650 |
| Reported | 2020-11-17 03:31:00 +0100 |
| Modified | 2020-11-17 03:31:27 +0100 |
| Product | Other Modules |
| Component | all |
| Version | unspecified |
| Platform | PC |
| OS | Windows |
| Status | ASSIGNED |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Brent Easton](mailto:b.easton@exemail.com.au) |
| Assignee | [Brent Easton](mailto:b.easton@exemail.com.au) |
| CC | arichbourg@sbcglobal.net |

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2020-11-17 03:31:17 +0100
<pre>We've just started our first game using it and run into a code problem. We're using Vassal 3.4.6 and the v27 module. The problems are in the Initiative button code, apparently. First, the impulse markers do not take into account the +1 for Kings. Second, the impulse markers move for the person hitting the Initiative button, but they remain at 0 when the opponent loads the vlog file. And finally, there is an Out of Date Custom Code error that sometimes comes up when hitting the button. I could send you a pic of the error dialog box via email if you like.

I also see this in the main Vassal window when starting a new game:

- [Out Of Date Custom Code] This module contains outdated custom code, which is not guaranteed to work with versions of VASSAL released after 6-Aug-2021.
- [Out Of Date Custom Code] Please check whether there is an updated version of this module. If not, please contact the maintainer of this module and request that it be fixed, or post a message on the Vassal forums and ask for help.

It's all easy enough to work around (apparently), but I thought I'd let you know. Any help would be much appreciated.

Cheers,
Alan Richbourg
arichbourg@sbcglobal.net</pre>

**Comment by BrentEaston** [comment]
Resolved with v2.8 of the module (Compatible with Vassal 3.6+)
