### ISSUE TITLE
ABR: [VASL] NullPointerException: Cannot invoke "VASL.LOS.Map.Hex.getNearestLocation(int, int)" because "h" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2488]
| Bugzilla |  |
|----------|----------|
| ID | BZ14497 |
| Reported | 2021-05-16 00:03:00 +0200 |
| Modified | 2021-05-16 02:27:17 +0200 |
| Product | VASL |
| Component | All |
| Version | 6.6.2 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/12986) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-16 00:03:00 +0200 text/plain 11092 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-16 00:03:45 +0200
<pre>chuck.tewksbury@gmail.com

checking LOS on a deluxe board	

VASL v6.6.2 3.5.5

java.lang.NullPointerException: Cannot invoke "VASL.LOS.Map.Hex.getNearestLocation(int, int)" because "h" is null
 at VASL.LOS.VASLGameInterface.updatePiece(VASLGameInterface.java:184)
 at VASL.LOS.VASLGameInterface.updatePieces(VASLGameInterface.java:112)
 at VASL.build.module.map.VASLThread.initializeMap(VASLThread.java:144)
 at VASL.build.module.map.VASLThread.launch(VASLThread.java:125)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-16 00:03:46 +0200
<pre>Created attachment 12986
the errorLog</pre>

**Comment by derimmer** [comment]
Fixed by VASL PR#970 and #972
