### ISSUE TITLE
ABR: [VASL] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2489]
| Bugzilla |  |
|----------|----------|
| ID | BZ14517 |
| Reported | 2021-05-24 16:34:00 +0200 |
| Modified | 2021-05-25 00:11:31 +0200 |
| Product | VASL |
| Component | All |
| Version | 6.6.2 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |
| CC | brian@brianreynolds.net |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/13002) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-24 16:34:00 +0200 text/plain 17058 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-24 16:34:18 +0200
<pre>Trying to setup an offline game with a board I had not downloaded previously.

VASL v6.6.2 3.5.5

java.lang.NullPointerException: null
 at VASL.build.module.map.boardPicker.ASLBoard.isLegacyBoard(ASLBoard.java:181)
 at VASL.build.module.map.boardPicker.VASLBoard.getName(VASLBoard.java:139)
 at VASL.build.module.ASLMap.setBoards(ASLMap.java:182)
 at VASSAL.build.module.map.BoardPicker.setup(BoardPicker.java:484)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-24 16:34:19 +0200
<pre>Created attachment 13002
the errorLog</pre>

**Comment by derimmer** [comment]
Transferred to VASL as #984
