### ISSUE TITLE
ABR: [VASL] IllegalArgumentException: scale = 0.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2527]
| Bugzilla |  |
|----------|----------|
| ID | BZ14571 |
| Reported | 2021-06-08 18:18:00 +0200 |
| Modified | 2021-06-08 18:18:11 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | 3.5.7 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/13045) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-08 18:18:00 +0200 text/plain 152158 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-08 18:18:10 +0200
<pre>jeff.wilson.mt@gmail.com

Trying to join a game to watch, the board was not available from the server looks like, probably not a bug - looks like it's a custom deal.

VASL v6.6.2 3.5.7

java.lang.IllegalArgumentException: scale = 0.0
 at VASSAL.tools.imageop.RotateScaleOpBitmapImpl.<init>(RotateScaleOpBitmapImpl.java:75)
 at VASSAL.tools.imageop.RotateScaleOpBitmapImpl.<init>(RotateScaleOpBitmapImpl.java:59)
 at VASSAL.tools.imageop.Op.rotateScale(Op.java:117)
 at VASSAL.counters.FreeRotator.draw(FreeRotator.java:302)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-08 18:18:11 +0200
<pre>Created attachment 13045
the errorLog</pre>

**Comment by derimmer** [comment]
@uckelman I had trouble finding this one - if I filter the list by the VASL label it does not show up (and yet it appears to be so labelled) and if I look at the full list, it is not in numerical order so it makes these hard to find. What sort order is used for the full list of Open Issues?

**Comment by derimmer** [comment]
according to the error log, this results from an unhandled error in ASLMap.drawPiecesNonStackableInRegion line 512. 

Transferred to VASL as #1018

**Comment by uckelman** [comment]
> @uckelman I had trouble finding this one - if I filter the list by the VASL label it does not show up (and yet it appears to be so labelled) and if I look at the full list, it is not in numerical order so it makes these hard to find. What sort order is used for the full list of Open Issues?

I'm not seeing what you're seeing---they're sorted in descending numerical order for me.

**Comment by derimmer** [comment]
Here is my list. I have looked at the Sort dropdown and I have Newest checked. There does not appear to be a by "#number" sort order option.
![sortsnip](https://user-images.githubusercontent.com/7696161/139732896-2089b4bb-9e3b-482b-9030-efb7ed61304a.PNG)

**Comment by uckelman** [comment]
Newest is the same thing as descending numeric order.
