### ISSUE TITLE
[Commands & Colors: Ancients] Scenario 107 Granicus - Wrong Setup

### ISSUE THREAD

**Issue by utechle** [vassalengine/modules#2621]
Please compare with the following excerpt from the scenario book:

![grafik](https://user-images.githubusercontent.com/113963843/191354510-666e1396-55ab-443d-bea6-6cdf382687cd.png)

And with this comment, respectively: https://www.commandsandcolors.net/ancients/forum-main.html?view=topic&catid=19&id=38#3963

**Comment by riverwanderer** [comment]
Thanks for reporting, sorry I only just picked it up. The scenario will be fixed in the next release of the module.

**Comment by riverwanderer** [comment]
Fixed in module release v4.3.
