### ISSUE TITLE
NPE in Red Star Rising custom code

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#861]
| Bugzilla |  |
|----------|----------|
| ID | BZ9375 |
| Reported | 2012-10-08 05:56:00 +0200 |
| Modified | 2012-11-14 17:26:09 +0100 |
| Product | Other Modules |
| Component | all |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) |
| CC | b.easton@exemail.com.au |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/8606) | [Joel Uckelman](mailto:uckelman@nomic.net) 2012-10-08 05:56:00 +0200 text/plain 6077 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-10-08 05:56:57 +0200
<pre>---- Reported by uckelman@nomic.net  ----

--- Bug imported by uckelman@nomic.net 2012-10-08 05:56 MST  ---

This bug was previously known as _bug_  at http://www.vassalengine.org/trackershow_bug.cgi?id=
Imported an attachment (id=8606)

The original submitter of attachment 8606 is unknown.
   Reassigning to the person who moved it here: uckelman@nomic.net.</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-10-08 13:57:32 +0200
<pre>*** Bug 9374 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-10-19 13:07:30 +0200
<pre>*** Bug 9418 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-10-19 13:07:48 +0200
<pre>*** Bug 9416 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-10-19 13:08:03 +0200
<pre>*** Bug 9391 has been marked as a duplicate of this bug. ***</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-11-14 17:26:09 +0100
<pre>*** Bug 9479 has been marked as a duplicate of this bug. ***</pre>

**Comment by BrentEaston** [comment]
See #2613 for latest updates
