### ISSUE TITLE
Bad custom code in Red Star Rising module

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#953]
| Bugzilla |  |
|----------|----------|
| ID | BZ9783 |
| Reported | 2013-01-28 22:02:00 +0100 |
| Modified | 2013-02-07 12:33:43 +0100 |
| Product | Other Modules |
| Component | all |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/9003) | [Joel Uckelman](mailto:uckelman@nomic.net) 2013-01-28 22:02:00 +0100 text/plain 6069 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2013-01-28 22:02:15 +0100
<pre>---- Reported by uckelman@nomic.net  ----

--- Bug imported by uckelman@nomic.net 2013-01-28 22:02 MST  ---

This bug was previously known as _bug_  at http://www.vassalengine.org/trackershow_bug.cgi?id=
Imported an attachment (id=9003)

The original submitter of attachment 9003 is unknown.
   Reassigning to the person who moved it here: uckelman@nomic.net.</pre>

**Comment by BrentEaston** [comment]
See #2613 for latest updates
